---
- name: creating user with variable
  hosts: all
  task:
    - name: create users
      user:
        name: "{{ my_user }}"
        state: present
    - name: install a package
      yum:
        name: "{{ my_pkg }}"
        state: present

